# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:13
    container_name: nestjs_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: mydatabase
      EMAIL_SERVICE: "smtp"
      EMAIL_USER: "your_email@gmail.com"
      EMAIL_PASS: "your_password"
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db-data:
